apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: basic-example
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: transform-status
    functionRef:
      name: function-status-transformer
    input:
      apiVersion: function-status-transformer.fn.crossplane.io/v1beta1
      kind: StatusTransformation
      statusConditionHooks:
        - matchers:
            - resources:
                - name: my-resource
              conditions:
                - type: Synced
                  status: "False"
          setConditions:
            - target: Composite
              condition:
                type: CustomReady
                status: "False"
                reason: ResourceNotSynced
                message: "The resource failed to sync"
