apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: events-example
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: transform-status
    functionRef:
      name: function-status-transformer
    input:
      apiVersion: function-status-transformer.fn.crossplane.io/v1beta1
      kind: StatusTransformation
      statusConditionHooks:
        - matchers:
            - resources:
                - name: my-database
              conditions:
                - type: Synced
                  status: "False"
                  reason: ReconcileError
                  # Capture the error message using a regex named group "Error"
                  message: "failed to create the database: (?P<Error>.+)"
          setConditions:
            - target: CompositeAndClaim
              condition:
                type: DatabaseReady
                status: "False"
                reason: FailedToCreate
                # Retrieve the captured variable into the new condition message
                message: "Encountered an error creating the database: {{ .Error }}"
          createEvents:
            - target: CompositeAndClaim
              event:
                type: Warning
                reason: FailedToCreate
                message: "Encountered an error creating the database: {{ .Error }}"
