---
apiVersion: example.crossplane.io/v1
kind: XR
metadata:
  name: example-xr
---
apiVersion: custom.example.com/v1alpha1
kind: MyDatabase
metadata:
  name: my-database-123
  annotations:
    crossplane.io/composition-resource-name: my-database
status:
  conditions:
  - type: Synced
    status: "False"
    reason: ReconcileError
    # This message perfectly matches the regex in composition.yaml:
    message: "failed to create the database: Invalid credentials provided to the engine."
