apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: advanced-example
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: transform-status
    functionRef:
      name: function-status-transformer
    input:
      apiVersion: function-status-transformer.fn.crossplane.io/v1beta1
      kind: StatusTransformation
      statusConditionHooks:
        # Match Scenario 1: ANY resource named cloudsql-* has a `Synced: False` condition
        - matchers:
            - type: AnyResourceMatchesAnyCondition
              resources:
                - name: "cloudsql-\\d+"
              conditions:
                - type: Synced
                  status: "False"
          setConditions:
            - target: Composite
              condition:
                type: GlobalSyncError
                status: "True"
                reason: OneOrMoreFailed
                message: "At least one CloudSQL instance failed to sync"
        
        # Match Scenario 2: ALL resources named cloudsql-* have a `Ready: True` condition AND a `Synced: True` condition
        - matchers:
            - type: AllResourcesMatchAllConditions
              resources:
                - name: "cloudsql-\\d+"
              conditions:
                - type: Synced
                  status: "True"
                - type: Ready
                  status: "True"
          setConditions:
            - target: Composite
              condition:
                type: CustomReady
                status: "True"
                reason: AllInstancesReady
                message: "All CloudSQL instances are online and synced."
