---
apiVersion: example.crossplane.io/v1
kind: XR
metadata:
  name: example-xr
---
apiVersion: database.example.com/v1alpha1
kind: CloudSQL
metadata:
  name: instance-1
  annotations:
    crossplane.io/composition-resource-name: cloudsql-1
status:
  conditions:
  - type: Synced
    status: "True"
    reason: ReconcileSuccess
  - type: Ready
    status: "True"
    reason: Online
---
apiVersion: database.example.com/v1alpha1
kind: CloudSQL
metadata:
  name: instance-2
  annotations:
    crossplane.io/composition-resource-name: cloudsql-2
status:
  conditions:
  - type: Synced
    status: "False"
    reason: ReconcileError
    message: "Network Timeout"
  - type: Ready
    status: "Unknown"
    reason: Provisioning
